### ISSUE TITLE
How to handle sub-instancing?

### ISSUE THREAD

**Issue by GitMoDu** [wizard97/ArduinoProcessScheduler#14]
Since the Process constructor requires the scheduler reference, how can I add a process to the scheduler inside the a custom Process class? The Arduino C/++ limitations are kind of hard on these issues.

**Comment by wizard97** [comment]
If the parent process already knows the child processes it needs during construction, you should should create the child process during the parents process' construction. This will avoid the use of heap memory, which is preferred for embedded platforms with no mmu.  You will need to use an initialization list by passing in the Scheduler reference argument.

If you must dynamically allocate new processes (aka using the new keyword), you can get the reference you need with just be calling `scheduler()`:

`inline Scheduler &scheduler() { return _scheduler; } `

**Comment by wizard97** [comment]
Yeah, that's correct you can just directly pass the same reference in. You're very close:

You use the initialization list in your .cpp, it should look something like this: 
```c++
ProcessMain(scheduller, PRIORITY, PERIOD) : Sub(scheduller,PRIORITY,PERIOD)
{
// Parents constructor implementation here
}
```

**Comment by wizard97** [comment]
Alternatively, could we have instances of projects where we only "attach" them to the scheduler on run-time (Setup(Scheduler)) without allocating heap memory?

The problem with that approach is the way it is designed is the user never should manually need to  call setup as the scheduler calls it automatically when needed. It's not even possible either because setup is a protected method. Also, this would force the use of scheduler pointers instead of references which are more prone to errors the compiler won't complain about.

**Comment by wizard97** [comment]
I'm glad you got child processes working, there definitely need to be a ton more examples. I have just been too lazy to do them myself...

Let me know if you have any more issues.
Aaron

**Comment by GitMoDu** [comment]
As promised, I've requested a pull of the sub-instancing example.
